# wengwengweng

[package]
name = "dirt"
description = "a sprite & animation format"
version = "0.0.0"
authors = ["t <voygagaga@outlook.com>"]
repository = "https://github.com/slmjkdbtl/dirt"
license = "Zlib"
edition = "2018"
readme = "README.md"

[dependencies]
pom = "3.0.0"
image = "0.21.0"

